= Rest API Exercises

== Verbs, actions and HTTP status codes

=== List all superheros

[source, json]
----
"/superheros": {
  "get": {
    "summary": "list all superheros",
    "description": "",
    "responses": {
      "200": {
        "description": "Not Found"
      },
      "404": {
        "description": "OK"
      }
    }
  }
----


=== Add superhero Spiderman

Some data about Spiderman:

[source, json]
----
{
    name: 'spiderman',
    hasCape: false
}
----
Notes:


* We don't know Spiderman's ID by now
* The input might be wrong (e.g. an invalid property). What is a proper response? What should this response contain?
* What is a proper response from the call?
* Are there any special HTTP header we should specify in the response?
* Spiderman is currently in no team, he might join one later...


[source, json]
----
"/superheros": {
"post": {
    "summary": "Add a new superhero",
    "parameters": [
      {
        "in": "body",
        "name": "body",
        "description": "Superhero which is added to the store",
        "required": true,
        "schema": {
          "$ref": "#/definitions/superHero"
        }
      }
    ],
    "responses": {
      "201": {
        "description": "Created",
        "schema": {
          "$ref": "#/definitions/superHero_withID"
        },
        "headers": {
          "Location": {
            "description": "superhero/34",
            "type": "string"
          }
        }
      },
      "400": {
        "description": "Invalid input",
        "schema": {
          "$ref": "#/definitions/validation_error"
        }
      }
    }
}
----

Sources:

* https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[HTTP status codes]
* https://stackoverflow.com/questions/19199872/best-practice-for-restful-post-response[POST response]
* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#useful-post-responses[POST response #2]
* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#Errors[Validation errors]

=== Spiderman needs to fight someone. Add his nemesis "Venom"
Some data about the super villain Venom:

[source, json]
----
{
    name: 'Venom',
    scaleOfEvil: 4
}
----
Notes:

* Venom's ID is defined as 'veom' (first two and last two letters of the name)
* In this example we don't care about input validation
* We would prefer an idempotent call.


[source, json]
----
"/super-villains": {
  "put": {
    "summary": "Add a new super villain",
    "parameters": [
      {
        "in": "body",
        "name": "body",
        "description": "Super villain ",
        "required": true,
        "schema": {
          "$ref": "#/definitions/superVillain"
        }
      }
    ],
    "responses": {
      "201": {
        "description": "Created",
        "schema": {
          "$ref": "#/definitions/superVillain"
        },
        "headers": {
          "Location": {
            "description": "super-villain/veom",
            "type": "string"
          }
        }
      }
    }
  }
}
----

* https://stackoverflow.com/questions/630453/put-vs-post-in-rest[PUT vs. POST]
* https://stackoverflow.com/questions/797834/should-a-restful-put-operation-return-something[PUT response value]

=== We would like to see all of Wonder Womans enemies
Notes:

* We also want to see the abilities of the super villains - find a way to define such
* The specified superhero might not exist

[source, json]
----
"/superheros/{superheroId}/super-villains": {
  "get": {
    "summary": "list all enemies of a superhero",
    "description": "",
    "parameters": [
      {
        "in": "path",
        "name": "superheroId",
        "description": "ID of the superhero",
        "required": true,
        "type": "integer"
      },
      {
        "in": "query",
        "name": "embed",
        "description": "Load related resource representations",
        "required": true,
        "type": "string",
        "format": "string",
        "default": "dummy"
      }
    ],
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "$ref": "#/definitions/superVillains_withAttributes"
        }
      },
      "404": {
        "description": "Superhero not Found"
      }
    }
  }
}
----

* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#autoloading[Auto loading related resource]
