:solutiondir: ./
= Verbs, actions and HTTP status codes


=== Intro
* A colleague asked your opinion about this request to create a resource

    GET /superceros/create?id=23&name=antman&hasCape=true

What you answer him? What problems do you see?

* You told him his solution might not yet be perfect so he changed the request to a POST. What about it now?

 POST  /superheros/create-hero


* Sometimes is not so easy to fit actions to the CRUD world. Example Github: how do you implement the `star` `unstar` action of a repository?

  PUT /gists/:id/star
  DELETE /gists/:id/star

Sources:

* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful[non CRUD actions]




=== Add superhero Spiderman

We would like to create the new superhero-resource *Spiderman*.
Describe the request & response as well as HTTP codes and useful headers.


*Notes*

* We don't know Spiderman's ID by now
* The input might be wrong (e.g. an invalid property). What is a proper response? What should this response contain?
* What is a proper response from the call?
* Are there any special HTTP header we should specify in the response?
* Spiderman is currently in no team, he might join one later...

Some data about Spiderman:

[source, json]
----
{
    name: 'spiderman',
    hasCape: false
}
----

[source,json]
----
include::{solutiondir}solution_1.json[]
----

Sources:

* https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[HTTP status codes]
* https://stackoverflow.com/questions/19199872/best-practice-for-restful-post-response[POST response]
* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#useful-post-responses[POST response #2]
* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#Errors[Validation errors]

=== Spiderman needs to fight someone. Add his nemesis "Venom"

Describe the request & response as well as HTTP codes and useful headers.

*Notes*

* Venom's ID is defined as `veom` (first two and last two letters of the name)
* In this example we don't care about input validation
* We would prefer an idempotent call.

Some data about the super villain Venom:

[source, json]
----
{
    name: 'Venom',
    scaleOfEvil: 4
}
----


[source,json]
----
include::{solutiondir}solution_2.json[]
----

* https://stackoverflow.com/questions/630453/put-vs-post-in-rest[PUT vs. POST]
* https://stackoverflow.com/questions/797834/should-a-restful-put-operation-return-something[PUT response value]

=== We would like to see all superheros of team "Fantastic Four"
Describe the request & response as well as HTTP codes and useful headers.

*Notes*:

* The specified superhero team id might not exist
* _Advanced_ We also want to see the abilities of the superheros - find a way to define this in the request

[source,json]
----
include::{solutiondir}solution_3.json[]
----

* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#autoloading[Auto loading related resource]

=== Filtering & sorting superheors
We would like to see all superheros which fight _Ares_ and have a cape.
Furthermore they should get sorted by name in descending order.

_Advanced_: How would you model a full text search on the `superhero` resource? (e.g. for an Elastic Search use case)


[source,json]
----
include::{solutiondir}solution_4.json[]
----

* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#advanced-queries[filtering & sorting]


=== Our superheros learn HATEOAS...
Extend the `superhero` resource *Wonder Woman* with stateful links so that an intelligent client can use the API without any prior know-how.
Use the http://stateless.co/hal_specification.html[HAL format].

[source,json]
----

----


Further questions:

* What advantages/disadvantages do you see in a level 3 REST API?
* Do you know largely used API's which already support the HATEOAS standard?

 * https://opencredo.com/hal-hypermedia-api-spring-hateoas/[hateoas]
 * https://opencredo.com/hal-hypermedia-api-spring-hateoas/[hateoas #2]
 * http://projects.spring.io/spring-hateoas[Spring hateoas]


