:solutiondir: ./
== Solutions

=== Resources

. superheroes, teams, abilities, supervillains +
swagger json
[source,json]
----
include::{solutiondir}resource_1.json[]
----
. there are many valid ways of defining it: super-villains, supervillains, superVillains, super_villains

TIP: define in an early stage if you want to use camel-case, dashorized or snake-case resources

. From the perspective of the superhero to fetch which are his oppenent supervillains?
.. e.g.[context]/superheroes/503/super-villains/ to fetch 'Thor's supervillains 'Man-Ape'

=== Verbs
====  Partial Updates

. The Server needs to to be able to decide if you set a field to ```null``` or if you want to only update partially.
. swagger json
[source,json]
----
include::{solutiondir}partial_updates.json[]
----

TIP: http://restful-api-design.readthedocs.io/en/latest/methods.html#patch-vs-put[PATCH VS. PUT] +
     https://www.greenbytes.de/tech/webdav/rfc7240.html#return[Advanced return definition]


== Pagination

. number of elements, tot alamount of elements, limit, (optional sort and order)
.
[source,json]
----
include::{solutiondir}pagination_1.json[]
----

== Versioning

. Either in URL or in header

TIP: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#versioning